# Generated by Django 5.1.4 on 2024-12-20 08:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='example-slug'),
            preserve_default=False,
        ),
    ]
